<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = ['entreprise', 'agence_voyages'];
        $categories = ['Premium', 'Direct', 'Revendeur'];
        $villes = ['Casablanca', "Rabat", "Tanger", "Safi", "Tetouan", "Nador", "Ouarzazat"];
        $jours = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'];

        $timestamp = time();
        $clients = [
            [
                'CodeClient' => 'C'.$timestamp.'001',
                'raison_sociale' => 'Client A',
                'adresse' => '123 Rue Example, Casablanca',
                'type_organisation' => $types[1],
                'categorie' => $categories[0],
                'tele' => '0612345678',
                'jour' => $jours[0],
                'ville' => $villes[0],
                'mod_id' => 1,
                'abreviation' => 'CA',
                'code_postal' => '20000',
                "montant_plafond" => 1000,
                "secteur_id" => 1,
                "seince" => 20,
                'ice' => rand(10000000, 99999999),
                'user_id' => 1,
                'zone_id' => 1,
                'region_id' => 1,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'002',
                'raison_sociale' => 'Client B',
                'adresse' => '456 Rue Example, Rabat',
                'type_organisation' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0623456789',
                'ville' => $villes[1],
                'jour' => $jours[1],
                'abreviation' => 'RB',
                'mod_id' => 1,
                "montant_plafond" => 1100,
                "seince" => 40,
                'code_postal' => '10000',
                'ice' => 23456789,
                'user_id' => 1,
                'zone_id' => 2,
                'region_id' => 2,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'003',
                "secteur_id" => 2,
                'raison_sociale' => 'Client C',
                'adresse' => '789 Rue Example, Marrakech',
                'type_organisation' => $types[1],
                'categorie' => $categories[2],
                'tele' => '0634567890',
                'ville' => $villes[3],
                'jour' => $jours[2],
                "seince" => 20,
                "montant_plafond" => 2000,
                'mod_id' => 1,
                'abreviation' => 'MC',
                'code_postal' => '40000',
                'ice' => 34567890,
                'user_id' => 1,
                'zone_id' => 3,
                'region_id' => 3,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'004',
                'raison_sociale' => 'Client D',
                'adresse' => '321 Rue Example, Fes',
                'type_organisation' => $types[0],
                'categorie' => $categories[0],
                'tele' => '0645678901',
                "seince" => 20,
                'ville' => $villes[4],
                "secteur_id" => 2,
                "montant_plafond" => 3000,
                'mod_id' => 1,
                'jour' => $jours[3],
                'abreviation' => 'FD',
                'code_postal' => '30000',
                'ice' => 45678901,
                'user_id' => 1,
                'zone_id' => 4,
                'region_id' => 4,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'005',
                'raison_sociale' => 'Client E',
                'adresse' => '654 Rue Example, Agadir',
                'type_organisation' => $types[1],
                'categorie' => $categories[1],
                "secteur_id" => 2,
                'tele' => '0656789012',
                "montant_plafond" => 1100,
                "seince" => 60,
                'ville' => $villes[3],
                'jour' => $jours[4],
                'abreviation' => 'AE',
                'mod_id' => 1,
                'code_postal' => '80000',
                'ice' => 56789012,
                'user_id' => 1,
                'zone_id' => 5,
                'region_id' => 5,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'006',
                'raison_sociale' => 'Client F',
                'adresse' => '987 Rue Example, Tanger',
                'type_organisation' => $types[0],
                'categorie' => $categories[2],
                "secteur_id" => 2,
                'tele' => '0667890123',
                'ville' => $villes[3],
                'mod_id' => 1,
                'jour' => $jours[5],
                "seince" => 20,
                "montant_plafond" => 1100,
                'abreviation' => 'TF',
                'code_postal' => '90000',
                'ice' => 67890123,
                'user_id' => 1,
                'zone_id' => 6,
                'region_id' => 6,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'007',
                'raison_sociale' => 'Client G',
                'adresse' => '135 Rue Example, Oujda',
                'type_organisation' => $types[1],
                "secteur_id" => 1,
                'categorie' => $categories[0],
                'tele' => '0678901234',
                'ville' => $villes[2],
                "seince" => 40,
                'mod_id' => 2,
                'jour' => $jours[6],
                'abreviation' => 'OG',
                "montant_plafond" => 1100,
                'code_postal' => '60000',
                'ice' => 78901234,
                'user_id' => 1,
                'zone_id' => 7,
                'region_id' => 7,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'008',
                'raison_sociale' => 'Client H',
                'adresse' => '246 Rue Example, Kenitra',
                'type_organisation' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0689012345',
                'ville' => $villes[1],
                'jour' => $jours[0],
                'abreviation' => 'KH',
                "seince" => 40,
                "montant_plafond" => 1100,
                'code_postal' => '14000',
                'ice' => 89012345,
                'user_id' => 1,
                'mod_id' => 2,
                'zone_id' => 8,
                'region_id' => 8,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'009',
                'raison_sociale' => 'Client I',
                'adresse' => '357 Rue Example, Settat',
                'type_organisation' => $types[1],
                'categorie' => $categories[2],
                'tele' => '0690123456',
                'ville' => $villes[0],
                'jour' => $jours[1],
                "montant_plafond" => 1100,
                "secteur_id" => 1,
                'abreviation' => 'SI',
                "seince" => 20,
                'code_postal' => '26000',
                'ice' => 90123456,
                'mod_id' => 2,
                'user_id' => 1,
                'zone_id' => 9,
                'region_id' => 9,
            ],
            [
                'CodeClient' => 'C'.$timestamp.'010',
                'raison_sociale' => 'Client J',
                'adresse' => '468 Rue Example, Safi',
                'type_organisation' => $types[0],
                'categorie' => $categories[0],
                'tele' => '0701234567',
                'ville' => $villes[0],
                "montant_plafond" => 1100,
                'jour' => $jours[2],
                'abreviation' => 'SJ',
                'code_postal' => '46000',
                'ice' => 12345678,
                "seince" => 20,
                'mod_id' => 1,
                "secteur_id" => 1,
                'user_id' => 1,
                'zone_id' => 10,
                'region_id' => 10,
            ],
        ];

        foreach ($clients as $client) {
            try {
                DB::table('clients')->insert(array_merge($client, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            } catch (\Exception $e) {
                // Skip if duplicate entry
                continue;
            }
        }
    }
}
