<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ClientParticulier;
use Illuminate\Support\Facades\DB;

class ClientParticulierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = time();
        $types = ['Prospect', 'Client'];
        $categories = ['Premium', 'Direct', 'Revendeur'];
        $villes = ['Casablanca', "Rabat", "Tanger", "Safi", "Tetouan", "Nador", "Ouarzazat"];

        $clients = [
            [
                'CodeClient' => 'CP'.$timestamp.'001',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJKZ',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '123 Rue Example, Casablanca',
                'type_client' => $types[1],
                'categorie' => $categories[0],
                'tele' => '0612345678',
                'ville' => $villes[0],
                'mod_id' => 1,
                'abreviation' => 'CA',
                'code_postal' => '20000',
                "montant_plafond" => 1000,
                "secteur_id" => 1,
                "seince" => 20,
                'user_id' => 1,
                'zone_id' => 1,
                'region_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'002',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJKZZ',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '456 Rue Example, Rabat',
                'type_client' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0623456789',
                'ville' => $villes[1],
                'abreviation' => 'RB',
                'mod_id' => 1,
                "montant_plafond" => 1100,
                "seince" => 40,
                'code_postal' => '10000',
                'user_id' => 1,
                'zone_id' => 2,
                'region_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'003',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                "secteur_id" => 2,
                'adresse' => '789 Rue Example, Marrakech',
                'type_client' => $types[1],
                'categorie' => $categories[2],
                'tele' => '0634567890',
                'ville' => $villes[3],
                "seince" => 20,
                "montant_plafond" => 2000,
                'mod_id' => 1,
                'abreviation' => 'MC',
                'code_postal' => '40000',
                'user_id' => 1,
                'zone_id' => 3,
                'region_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'004',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJ2K3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '321 Rue Example, Fes',
                'type_client' => $types[0],
                'categorie' => $categories[0],
                'tele' => '0645678901',
                "seince" => 20,
                'ville' => $villes[4],
                "secteur_id" => 2,
                "montant_plafond" => 3000,
                'mod_id' => 1,
                'abreviation' => 'FD',
                'code_postal' => '30000',
                'user_id' => 1,
                'zone_id' => 4,
                'region_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'005',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK2143E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '654 Rue Example, Agadir',
                'type_client' => $types[1],
                'categorie' => $categories[1],
                "secteur_id" => 2,
                'tele' => '0656789012',
                "montant_plafond" => 1100,
                "seince" => 60,
                'ville' => $villes[3],
                'abreviation' => 'AE',
                'mod_id' => 1,
                'code_postal' => '80000',
                'user_id' => 1,
                'zone_id' => 5,
                'region_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'006',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BEDJK213E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '987 Rue Example, Tanger',
                'type_client' => $types[0],
                'categorie' => $categories[2],
                "secteur_id" => 2,
                'tele' => '0667890123',
                'ville' => $villes[3],
                'mod_id' => 1,
                "seince" => 20,
                "montant_plafond" => 1100,
                'abreviation' => 'TF',
                'code_postal' => '90000',
                'user_id' => 1,
                'zone_id' => 6,
                'region_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'007',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BE12JK3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '135 Rue Example, Oujda',
                'type_client' => $types[1],
                "secteur_id" => 1,
                'categorie' => $categories[0],
                'tele' => '0678901234',
                'ville' => $villes[2],
                "seince" => 40,
                'mod_id' => 2,
                'abreviation' => 'OG',
                "montant_plafond" => 1100,
                'code_postal' => '60000',
                'user_id' => 1,
                'zone_id' => 7,
                'region_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'008',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BE291K3E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '246 Rue Example, Kenitra',
                'type_client' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[1],
                'tele' => '0689012345',
                'ville' => $villes[1],
                'abreviation' => 'KH',
                "seince" => 40,
                "montant_plafond" => 1100,
                'code_postal' => '14000',
                'user_id' => 1,
                'mod_id' => 2,
                'zone_id' => 8,
                'region_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'009',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BED1453E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '357 Rue Example, Meknes',
                'type_client' => $types[1],
                "secteur_id" => 1,
                'categorie' => $categories[2],
                'tele' => '0690123456',
                'ville' => $villes[1],
                'abreviation' => 'MK',
                "seince" => 40,
                "montant_plafond" => 1100,
                'code_postal' => '50000',
                'user_id' => 1,
                'mod_id' => 2,
                'zone_id' => 9,
                'region_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CodeClient' => 'CP'.$timestamp.'010',
                'name' => 'Alaoui',
                'prenom' => 'Mohamed',
                'cin' => 'BED1453E',
                'civilite' => 'Monsieur',
                'nationalite' => 'Marocain',
                'adresse' => '468 Rue Example, Tetouan',
                'type_client' => $types[0],
                "secteur_id" => 1,
                'categorie' => $categories[0],
                'tele' => '0601234567',
                'ville' => $villes[4],
                'abreviation' => 'TT',
                "seince" => 40,
                "montant_plafond" => 1100,
                'code_postal' => '93000',
                'user_id' => 1,
                'mod_id' => 2,
                'zone_id' => 10,
                'region_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($clients as $client) {
            try {
                DB::table('clients_particulier')->insert($client);
            } catch (\Exception $e) {
                // Skip if duplicate entry
                continue;
            }
        }
    }
}
